#配置数据源
spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          type: com.alibaba.druid.pool.DruidDataSource
          driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
          url: jdbc:log4jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/${DB_NAME:master_ads}?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
          username: ${DB_USER:root}
          password: ${DB_PWD:hx210420}
          druid:
            # 初始连接数
            initial-size: 5
            # 最小连接数
            min-idle: 15
            # 最大连接数
            max-active: 30
            # 超时时间(以秒数为单位)
            remove-abandoned-timeout: 180
            # 获取连接超时时间
            max-wait: 3000
            # 连接有效性检测时间
            time-between-eviction-runs-millis: 60000
            # 连接在池中最小生存的时间
            min-evictable-idle-time-millis: 300000
            # 连接在池中最大生存的时间
            max-evictable-idle-time-millis: 900000
            # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除
            test-while-idle: false
            # 指明是否在从池中取出连接前进行检验,如果检验失败, 则从池中去除连接并尝试取出另一个
            test-on-borrow: true
            # 是否在归还到池中前进行检验
            test-on-return: false
            # 检测连接是否有效
            validation-query: select 1
            # 配置监控统计
#            webStatFilter:
#              enabled: true
#            stat-view-servlet:
#              enabled: true
#              url-pattern: /druid/*
#              reset-enable: false
#            filter:
#              stat:
#                enabled: true
#                # 记录慢SQL
#                log-slow-sql: true
#                slow-sql-millis: 1000
#                merge-sql: true
#              wall:
#                config:
#                  multi-statement-allow: true
        wangmeng:
          type: com.alibaba.druid.pool.DruidDataSource
          driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
          url: jdbc:log4jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/${DB_NAME:master_ads}?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
          username: ${DB_USER:root}
          password: ${DB_PWD:hx210420}
#          url: jdbc:log4jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/${DB_NAME:master_ads}?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
#          username: ${DB_USER:root}
#          password: ${DB_PWD:hx210420}
          druid:
            # 初始连接数
            initial-size: 5
            # 最小连接数
            min-idle: 15
            # 最大连接数
            max-active: 30
            # 超时时间(以秒数为单位)
            remove-abandoned-timeout: 180
            # 获取连接超时时间
            max-wait: 3000
            # 连接有效性检测时间
            time-between-eviction-runs-millis: 60000
            # 连接在池中最小生存的时间
            min-evictable-idle-time-millis: 300000
            # 连接在池中最大生存的时间
            max-evictable-idle-time-millis: 900000
            # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除
            test-while-idle: true
            # 指明是否在从池中取出连接前进行检验,如果检验失败, 则从池中去除连接并尝试取出另一个
            test-on-borrow: true
            # 是否在归还到池中前进行检验
            test-on-return: false
            # 检测连接是否有效
            validation-query: select 1
            # 配置监控统计
    #        webStatFilter:
    #          enabled: true
    #        stat-view-servlet:
    #          enabled: true
    #          url-pattern: /druid/*
    #          reset-enable: false
    #        filter:
    #          stat:
    #            enabled: true
    #            # 记录慢SQL
    #            log-slow-sql: true
    #            slow-sql-millis: 1000
    #            merge-sql: true
    #          wall:
    #            config:
    #              multi-statement-allow: true

#spring:
#  autoconfigure:
mybatis-plus:
  mapper-locations: "classpath:mapper/*.xml"
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: UAfauG9rrNdRyxhd8BZBPXfL8iJ413b1MagJZ0FxgU9FFaIGsLUAPMA8/2ynUkiBfVCfu0tRMiLZ/oU+A34ZaA==

oss:
  endpoint: http://oss-cn-shanghai.aliyuncs.com
  access_key_id: ${ALIYUN_OSS_ACCESS_KEY_ID}
  access_key_secret: ${ALIYUN_OSS_ACCESS_KEY_SECRET}
  bucket_name: yiyitech-ads
  folder: report/

translator:
  plan:
    mode: free   # 想切回免费就改成 free
  free_plan:
    bases: http://39.98.47.172:30003
    connectTimeoutMs: 5000
    readTimeoutMs: 20000
  doubao_plan:
    apiKey: ${DOUBAO_API_KEY:pause}   #若是占位符，则自动回退到免费
    endpoint: https://ark.cn-beijing.volces.com/api/v3/chat/completions
    model: doubao-lite-4k
  cache:
    size: 50000  # 可调
  rateLimit:
    qps: 5

swagger:
  enabled: true
  base-package: com.yiyitech
